export {
  CURRENT_STORAGE_SCHEMA_VERSION,
  DATABASE_APPLICATION_ID,
  REGISTERED_COLLECTIONS,
  createDatabaseSnapshot,
  exportDatabaseBackup,
  generateId,
  generateNumber,
  getAllMigrationMarkers,
  getMigrationMarker,
  importDatabaseBackup,
  initializeLocalDatabase,
  markMigrationFailure,
  markMigrationSuccess,
  migrateLegacyAppointmentStorage,
  migrateLegacyInventoryStorage,
  readCollection,
  resetDatabase,
  resetMigrationMarkers,
  restoreDatabaseSnapshot,
  runCompensatedOperation,
  runInTransaction,
  runInTransactionAsync,
  runMigratorWithRollback,
  runMigratorWithRollbackAsync,
  writeCollection,
} from '@engines/persistence';
export type {
  DatabaseMetadata,
  LocalDatabaseBackup,
  MigrationMarker,
  PersistenceSnapshot,
} from '@engines/persistence';
