import type { ExpenseRecord } from './expense.types';

export const expenseMockRecords: ExpenseRecord[] = [
  {
    id: 'exp-1',
    expenseNumber: 'EXP-2026-0501',
    expenseDate: '2026-05-03',
    title: 'تنظيف فساتين بعد موسم الأعراس',
    category: 'laundry',
    amount: 38,
    paymentMethod: 'cash',
    relatedDressCode: 'DR-021',
    relatedDressName: 'فستان سهرة كحلي',
    notes: 'تنظيف 4 فساتين شديدة الاستخدام.',
  },
  {
    id: 'exp-2',
    expenseNumber: 'EXP-2026-0502',
    expenseDate: '2026-05-05',
    title: 'تعديل مقاس فستان دانتيل',
    category: 'tailoring',
    amount: 14,
    paymentMethod: 'card',
    relatedDressCode: 'DR-011',
    relatedDressName: 'فستان دانتيل عاجي',
  },
  {
    id: 'exp-3',
    expenseNumber: 'EXP-2026-0503',
    expenseDate: '2026-05-08',
    title: 'صيانة سحاب فستان مخملي',
    category: 'maintenance',
    amount: 9.5,
    paymentMethod: 'cash',
    relatedDressCode: 'DR-025',
    relatedDressName: 'فستان مخملي أزرق',
    notes: 'استبدال السحاب الخلفي بالكامل.',
  },
  {
    id: 'exp-4',
    expenseNumber: 'EXP-2026-0504',
    expenseDate: '2026-05-12',
    title: 'شراء فستان جديد لمجموعة الصيف',
    category: 'purchase',
    amount: 185,
    paymentMethod: 'bank_transfer',
    relatedDressCode: 'DR-031',
    relatedDressName: 'فستان شيفون زمردي',
  },
  {
    id: 'exp-5',
    expenseNumber: 'EXP-2026-0505',
    expenseDate: '2026-05-14',
    title: 'إيجار المحل - مايو 2026',
    category: 'rent',
    amount: 450,
    paymentMethod: 'bank_transfer',
    notes: 'دفعة شهرية ثابتة.',
  },
  {
    id: 'exp-6',
    expenseNumber: 'EXP-2026-0506',
    expenseDate: '2026-05-16',
    title: 'رواتب فريق المتجر',
    category: 'salary',
    amount: 620,
    paymentMethod: 'bank_transfer',
    notes: 'راتب موظفتين + مساعدة دوام جزئي.',
  },
  {
    id: 'exp-7',
    expenseNumber: 'EXP-2026-0507',
    expenseDate: '2026-05-18',
    title: 'مواد تغليف وتسليم',
    category: 'other',
    amount: 27.75,
    paymentMethod: 'other',
    notes: 'أكياس حماية وعلب إكسسوارات.',
  },
];
