import { Link, useParams } from 'react-router-dom';
import { Printer, Shirt } from 'lucide-react';
import { PageHeader } from '../../components/shared/PageHeader';
import { SummaryCard } from '../../components/shared/SummaryCard';
import { formatMoneyOMR } from '../../shared/utils/format';
import { getDressLifecycle, getDressRecommendations } from './dressLifecycle.service';
import { getDresses } from './dress.service';
import { printDressLabel } from './printDressLabel';

const statusLabels: Record<string, string> = { available: 'متاح', reserved: 'محجوز', rented: 'مؤجر', laundry: 'في المغسلة', maintenance: 'تحت الفحص/الصيانة', damaged: 'تالف', sold: 'مباع', inactive: 'غير نشط' };

export function DressDetailsPage() {
  const { code = '' } = useParams();
  const dress = getDresses().find((item) => item.code === code);
  if (!dress) return <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Shirt className="mx-auto h-10 w-10 text-slate-400" /><h1 className="mt-4 text-2xl font-bold">الفستان غير موجود</h1><Link to="/dresses" className="mt-4 inline-flex rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white">العودة للمخزون</Link></section>;

  const lifecycle = getDressLifecycle(dress.code);
  const recommendations = getDressRecommendations(lifecycle);
  const performance = lifecycle.performance;

  return <section className="space-y-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><PageHeader eyebrow="ملف الفستان" title={`${dress.name} · ${dress.code}`} description="ملف واحد يربط الحجوزات والمبيعات والمرتجعات والمصروفات والخدمة وربحية القطعة." /><div className="flex flex-wrap gap-3"><button type="button" onClick={() => printDressLabel(dress)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white"><Printer className="h-5 w-5" />طباعة الملصق</button><Link to="/dresses" className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-bold">المخزون</Link></div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><SummaryCard label="إجمالي الإيراد" value={formatMoneyOMR(performance?.totalRevenue ?? 0)} /><SummaryCard label="المصروفات المرتبطة" value={formatMoneyOMR(performance?.relatedExpenses ?? 0)} /><SummaryCard label="صافي النتيجة" value={formatMoneyOMR(performance?.netResult ?? 0)} tone={(performance?.netResult ?? 0) >= 0 ? 'positive' : 'danger'} /><SummaryCard label="ROI" value={performance?.roiPercent === null || performance?.roiPercent === undefined ? 'غير متاح' : `${performance.roiPercent.toFixed(1)}%`} /></div>
    <div className="grid gap-5 xl:grid-cols-[320px_1fr]"><article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex min-h-80 items-center justify-center overflow-hidden bg-gradient-to-br from-violet-100 via-white to-amber-50">{dress.mainImageUrl ? <img src={dress.mainImageUrl} alt={`صورة ${dress.name}`} className="h-full max-h-[520px] w-full object-cover" /> : <div className="rounded-full bg-white/80 p-8 shadow-sm ring-1 ring-slate-200"><Shirt className="h-16 w-16 text-violet-700" /></div>}</div></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-extrabold">بيانات الفستان</h2><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p><b>الكود:</b> <span dir="ltr">{dress.code}</span></p><p><b>الحالة:</b> {statusLabels[dress.status]}</p><p><b>الوصف:</b> {dress.description || 'غير مسجل'}</p><p><b>الفئة:</b> {dress.category}</p><p><b>المقاس:</b> <span dir="ltr">{dress.size}</span></p><p><b>اللون:</b> {dress.color}</p><p><b>تكلفة الشراء:</b> {formatMoneyOMR(dress.purchasePrice)}</p><p><b>سعر الإيجار:</b> {formatMoneyOMR(dress.rentalPrice)}</p><p><b>سعر البيع:</b> {formatMoneyOMR(dress.salePrice)}</p><p><b>التأمين:</b> {formatMoneyOMR(dress.depositAmount)}</p><p><b>متاح للإيجار:</b> {dress.isForRent ? 'نعم' : 'لا'}</p><p><b>متاح للبيع:</b> {dress.isForSale ? 'نعم' : 'لا'}</p><p><b>عدد مرات الإيجار:</b> {dress.timesRented}</p><p><b>آخر حركة:</b> {performance?.lastMovementDate ?? 'لا توجد'}</p><p><b>أيام عدم الحركة:</b> {performance?.inactivityDays ?? 'غير متاح'}</p></div></article></div>
    <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-extrabold">توصيات تشغيلية</h2>{recommendations.length ? <ul className="mt-4 space-y-2">{recommendations.map((item) => <li key={item} className="rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-900">{item}</li>)}</ul> : <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">لا توجد توصيات حرجة حالياً.</p>}</article>
    <div className="grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-extrabold">الحركة المالية والتشغيلية</h2><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p><b>الحجوزات:</b> {lifecycle.reservations.length}</p><p><b>المبيعات:</b> {lifecycle.sales.length}</p><p><b>المرتجعات:</b> {lifecycle.returns.length}</p><p><b>المصروفات:</b> {lifecycle.expenses.length}</p><p><b>مهام الخدمة:</b> {lifecycle.serviceTasks.length}</p><p><b>استرداد تكلفة الشراء:</b> {performance?.recoveredPurchaseCost ? 'نعم' : 'لا'}</p></div></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-extrabold">الخط الزمني</h2>{lifecycle.timeline.length ? <div className="mt-4 space-y-2">{lifecycle.timeline.map((item, index) => <div key={`${item.date}-${item.label}-${index}`} className="flex items-center justify-between gap-3 rounded-xl bg-stone-50 p-3 text-sm"><span>{item.label}</span><b dir="ltr">{item.date}</b></div>)}</div> : <p className="mt-4 text-sm text-slate-500">لا توجد حركة مسجلة لهذا الفستان.</p>}</article></div>
  </section>;
}
