export const mockDresses = [
  {
    id: 'dress-001',
    code: 'D001',
    name: 'فستان سهرة كحلي',
    description: 'فستان سهرة أنيق مع تطريز كحلي',
    category: 'سهرة',
    color: 'كحلي',
    size: 'M',
    purchasePrice: 150,
    rentalPrice: 50,
    salePrice: 200,
    depositAmount: 20,
    status: 'available',
    isForRent: true,
    isForSale: false,
    images: [],
    barcode: 'DRESS-001',
    timesRented: 3,
    notes: 'فساتين مطلوبة كثيراً',
  },
  {
    id: 'dress-002',
    code: 'D002',
    name: 'فستان زفاف كلاسيك',
    description: 'فستان زفاف بتصميم كلاسيك أنيق',
    category: 'زفاف',
    color: 'أبيض',
    size: 'L',
    purchasePrice: 500,
    rentalPrice: 200,
    salePrice: 800,
    depositAmount: 100,
    status: 'reserved',
    isForRent: true,
    isForSale: false,
    images: [],
    barcode: 'DRESS-002',
    timesRented: 1,
  },
  {
    id: 'dress-003',
    code: 'D003',
    name: 'فستان خطوبة وردي',
    description: 'فستان خطوبة بلون وردي ناعم',
    category: 'خطوبة',
    color: 'وردي',
    size: 'S',
    purchasePrice: 120,
    rentalPrice: 40,
    salePrice: 180,
    depositAmount: 15,
    status: 'rented',
    isForRent: true,
    isForSale: true,
    images: [],
    barcode: 'DRESS-003',
    timesRented: 5,
  },
  {
    id: 'dress-004',
    code: 'D004',
    name: 'فستان أطفال زهري',
    description: 'فستان أطفال للمناسبات',
    category: 'أطفال',
    color: 'زهري',
    size: 'XS',
    purchasePrice: 80,
    rentalPrice: 30,
    salePrice: 120,
    depositAmount: 10,
    status: 'laundry',
    isForRent: true,
    isForSale: true,
    images: [],
    barcode: 'DRESS-004',
    timesRented: 2,
  },
  {
    id: 'dress-005',
    code: 'D005',
    name: 'فستان سهرة أسود',
    description: 'فستان سهرة أسود أنيق',
    category: 'سهرة',
    color: 'أسود',
    size: 'M',
    purchasePrice: 180,
    rentalPrice: 60,
    salePrice: 250,
    depositAmount: 25,
    status: 'available',
    isForRent: true,
    isForSale: false,
    images: [],
    barcode: 'DRESS-005',
    timesRented: 4,
    notes: 'كلاسيك ومميز',
  },
];
