import type { Dress } from './dress.types';

export const mockDresses: Dress[] = [
  {
    id: 'dress-001',
    code: 'DR-001',
    name: 'فستان سهرة بنفسجي ملكي',
    description: 'فستان سهرة مطرز بتفاصيل ناعمة وقصة مناسبة للمناسبات الرسمية.',
    category: 'سهرة',
    color: 'بنفسجي',
    size: 'M',
    purchasePrice: 120,
    rentalPrice: 25,
    salePrice: 190,
    depositAmount: 30,
    status: 'available',
    isForRent: true,
    isForSale: true,
    timesRented: 6,
    notes: 'الأكثر طلبًا في نهاية الأسبوع.',
  },
  {
    id: 'dress-002',
    code: 'DR-002',
    name: 'فستان زفاف أبيض كلاسيك',
    description: 'فستان زفاف أبيض بذيل طويل وتطريز بسيط.',
    category: 'زفاف',
    color: 'أبيض',
    size: 'L',
    purchasePrice: 350,
    rentalPrice: 80,
    salePrice: 520,
    depositAmount: 100,
    status: 'reserved',
    isForRent: true,
    isForSale: false,
    timesRented: 3,
  },
  {
    id: 'dress-003',
    code: 'DR-003',
    name: 'فستان خطوبة وردي ناعم',
    description: 'تصميم خفيف مناسب للخطوبة وجلسات التصوير.',
    category: 'خطوبة',
    color: 'وردي',
    size: 'S',
    purchasePrice: 160,
    rentalPrice: 35,
    salePrice: 240,
    depositAmount: 40,
    status: 'rented',
    isForRent: true,
    isForSale: true,
    timesRented: 8,
  },
  {
    id: 'dress-004',
    code: 'DR-004',
    name: 'فستان أطفال ذهبي',
    description: 'فستان أطفال للمناسبات العائلية، خفيف وسهل الحركة.',
    category: 'أطفال',
    color: 'ذهبي',
    size: '8Y',
    purchasePrice: 45,
    rentalPrice: 10,
    salePrice: 70,
    depositAmount: 15,
    status: 'laundry',
    isForRent: true,
    isForSale: true,
    timesRented: 11,
  },
  {
    id: 'dress-005',
    code: 'DR-005',
    name: 'فستان سهرة أسود فاخر',
    description: 'فستان أسود أنيق بقصة طويلة مناسب للحفلات الرسمية.',
    category: 'سهرة',
    color: 'أسود',
    size: 'M',
    purchasePrice: 140,
    rentalPrice: 30,
    salePrice: 210,
    depositAmount: 35,
    status: 'maintenance',
    isForRent: true,
    isForSale: false,
    timesRented: 5,
    notes: 'يحتاج مراجعة سحاب الظهر.',
  },
];
