export const mockDresses = [
  {
    id: 'dress-001',
    code: 'D001',
    name: 'فستان سهرة كحلي',
    description: 'فستان سهرة أنيق مع تطريز كحلي',
    itemType: 'dress',
    category: 'سهرة',
    color: 'كحلي',
    size: 'M',
    purchasePrice: 150,
    rentalPrice: 50,
    salePrice: 200,
    depositAmount: 20,
    status: 'available',
    isForRent: true,
    isForSale: false,
    images: [],
    barcode: 'DRESS-001',
    timesRented: 3,
    notes: 'فساتين مطلوبة كثيراً',
  },
  {
    id: 'dress-002',
    code: 'D002',
    name: 'فستان زفاف كلاسيك',
    description: 'فستان زفاف بتصميم كلاسيك أنيق',
    itemType: 'dress',
    category: 'زفاف',
    color: 'أبيض',
    size: 'L',
    purchasePrice: 500,
    rentalPrice: 200,
    salePrice: 800,
    depositAmount: 100,
    status: 'reserved',
    isForRent: true,
    isForSale: false,
    images: [],
    barcode: 'DRESS-002',
    timesRented: 1,
  },
  {
    id: 'dress-003',
    code: 'D003',
    name: 'فستان خطوبة وردي',
    description: 'فستان خطوبة بلون وردي ناعم',
    itemType: 'dress',
    category: 'خطوبة',
    color: 'وردي',
    size: 'S',
    purchasePrice: 120,
    rentalPrice: 40,
    salePrice: 180,
    depositAmount: 15,
    status: 'rented',
    isForRent: true,
    isForSale: true,
    images: [],
    barcode: 'DRESS-003',
    timesRented: 5,
  },
  {
    id: 'item-004',
    code: 'D004',
    name: 'حقيبة سهرة فضية',
    description: 'حقيبة مناسبة لفستان السهرة والمناسبات الرسمية',
    itemType: 'bag',
    category: 'حقائب',
    color: 'فضي',
    size: 'One Size',
    purchasePrice: 35,
    rentalPrice: 10,
    salePrice: 55,
    depositAmount: 5,
    status: 'available',
    isForRent: true,
    isForSale: true,
    images: [],
    barcode: 'ITEM-004',
    timesRented: 2,
  },
  {
    id: 'item-005',
    code: 'D005',
    name: 'تاج كريستال',
    description: 'إكسسوار مناسب للزفاف والخطوبة',
    itemType: 'accessory',
    category: 'إكسسوارات',
    color: 'فضي',
    size: 'One Size',
    purchasePrice: 20,
    rentalPrice: 8,
    salePrice: 35,
    depositAmount: 0,
    status: 'available',
    isForRent: true,
    isForSale: true,
    images: [],
    barcode: 'ITEM-005',
    timesRented: 4,
    notes: 'مناسب مع موديلات الزفاف',
  },
];
