import type { Customer } from './customer.types';

export const mockCustomers: Customer[] = [
  {
    id: 'customer-001',
    name: 'مريم البلوشي',
    phone: '9000-0001',
    address: 'مسقط، الخوير',
    measurements: 'الطول 165 سم، المقاس M',
    status: 'trusted',
    totalReservations: 6,
    activeReservations: 1,
    totalPaid: 210,
    remainingBalance: 0,
    lastReservationDate: '2026-05-12',
    notes: 'عميلة منتظمة وتلتزم بمواعيد الإرجاع.',
  },
  {
    id: 'customer-002',
    name: 'سارة الهنائية',
    phone: '9000-0002',
    address: 'السيب، المعبيلة',
    measurements: 'الطول 158 سم، المقاس S',
    status: 'normal',
    totalReservations: 2,
    activeReservations: 0,
    totalPaid: 65,
    remainingBalance: 15,
    lastReservationDate: '2026-04-28',
  },
  {
    id: 'customer-003',
    name: 'نورة العامرية',
    phone: '9000-0003',
    address: 'بوشر، الغبرة',
    measurements: 'الطول 170 سم، المقاس L',
    status: 'warning',
    totalReservations: 4,
    activeReservations: 1,
    totalPaid: 120,
    remainingBalance: 35,
    lastReservationDate: '2026-05-16',
    notes: 'تأخرت في الإرجاع مرة واحدة.',
  },
  {
    id: 'customer-004',
    name: 'هند الشكيلية',
    phone: '9000-0004',
    address: 'نزوى، فرق',
    measurements: 'المقاس M/L',
    status: 'normal',
    totalReservations: 1,
    activeReservations: 0,
    totalPaid: 30,
    remainingBalance: 0,
    lastReservationDate: '2026-03-20',
  },
  {
    id: 'customer-005',
    name: 'ليان المقبالية',
    phone: '9000-0005',
    address: 'صحار، الطريف',
    measurements: 'الطول 162 سم، المقاس M',
    status: 'blocked',
    totalReservations: 3,
    activeReservations: 0,
    totalPaid: 80,
    remainingBalance: 50,
    lastReservationDate: '2026-02-14',
    notes: 'لا يتم قبول حجز جديد قبل تسوية الرصيد.',
  },
];
