import type { Reservation } from './reservation.types';

export const mockReservations: Reservation[] = [
  {
    id: 'reservation-001',
    reservationNumber: 'RSV-001',
    customerName: 'مريم البلوشي',
    customerPhone: '9000-0001',
    dressCode: 'DR-001',
    dressName: 'فستان سهرة بنفسجي ملكي',
    pickupDate: '2026-05-19',
    returnDate: '2026-05-21',
    status: 'confirmed',
    rentalPrice: 25,
    depositAmount: 30,
    totalAmount: 55,
    paidAmount: 25,
    remainingAmount: 30,
    notes: 'استلام بعد العصر.',
  },
  {
    id: 'reservation-002',
    reservationNumber: 'RSV-002',
    customerName: 'نورة العامرية',
    customerPhone: '9000-0003',
    dressCode: 'DR-003',
    dressName: 'فستان خطوبة وردي ناعم',
    pickupDate: '2026-05-16',
    returnDate: '2026-05-18',
    status: 'overdue',
    rentalPrice: 35,
    depositAmount: 40,
    totalAmount: 75,
    paidAmount: 40,
    remainingAmount: 35,
    notes: 'تحتاج متابعة للاسترجاع.',
  },
  {
    id: 'reservation-003',
    reservationNumber: 'RSV-003',
    customerName: 'سارة الهنائية',
    customerPhone: '9000-0002',
    dressCode: 'DR-002',
    dressName: 'فستان زفاف أبيض كلاسيك',
    pickupDate: '2026-05-25',
    returnDate: '2026-05-27',
    status: 'pending',
    rentalPrice: 80,
    depositAmount: 100,
    totalAmount: 180,
    paidAmount: 0,
    remainingAmount: 180,
  },
  {
    id: 'reservation-004',
    reservationNumber: 'RSV-004',
    customerName: 'هند الشكيلية',
    customerPhone: '9000-0004',
    dressCode: 'DR-004',
    dressName: 'فستان أطفال ذهبي',
    pickupDate: '2026-05-10',
    returnDate: '2026-05-12',
    status: 'returned',
    rentalPrice: 10,
    depositAmount: 15,
    totalAmount: 25,
    paidAmount: 25,
    remainingAmount: 0,
  },
];
