import type { PaymentRecord } from './payment.types';

export const paymentMockRecords: PaymentRecord[] = [
  {
    id: 'pay-1',
    paymentNumber: 'PAY-2026-1001',
    reservationNumber: 'RES-2026-052',
    customerName: 'ريم خالد',
    dressCode: 'DR-025',
    dressName: 'فستان مخملي أزرق',
    paymentDate: '2026-05-18',
    type: 'deposit',
    method: 'cash',
    direction: 'income',
    amount: 150,
    reservationTotal: 320,
    notes: 'عربون تأكيد الحجز.',
  },
  {
    id: 'pay-2',
    paymentNumber: 'PAY-2026-1002',
    reservationNumber: 'RES-2026-052',
    customerName: 'ريم خالد',
    dressCode: 'DR-025',
    dressName: 'فستان مخملي أزرق',
    paymentDate: '2026-05-19',
    type: 'rental',
    method: 'card',
    direction: 'income',
    amount: 100,
    reservationTotal: 320,
    notes: 'دفعة جزئية من قيمة الإيجار.',
  },
  {
    id: 'pay-3',
    paymentNumber: 'PAY-2026-1003',
    reservationNumber: 'RES-2026-041',
    customerName: 'نور علي',
    dressCode: 'DR-008',
    dressName: 'فستان وردي مطرز',
    paymentDate: '2026-05-11',
    type: 'penalty',
    method: 'cash',
    direction: 'income',
    amount: 20,
    reservationTotal: 280,
    notes: 'رسوم تأخير يومين.',
  },
  {
    id: 'pay-4',
    paymentNumber: 'PAY-2026-1004',
    reservationNumber: 'RES-2026-039',
    customerName: 'هدى سمير',
    dressCode: 'DR-004',
    dressName: 'فستان أحمر ساتان',
    paymentDate: '2026-05-09',
    type: 'penalty',
    method: 'bank_transfer',
    direction: 'income',
    amount: 35,
    reservationTotal: 300,
    notes: 'رسوم ضرر بسبب تمزق بسيط.',
  },
  {
    id: 'pay-5',
    paymentNumber: 'PAY-2026-1005',
    reservationNumber: 'RES-2026-046',
    customerName: 'ليان مازن',
    dressCode: 'DR-011',
    dressName: 'فستان دانتيل عاجي',
    paymentDate: '2026-05-12',
    type: 'refund',
    method: 'cash',
    direction: 'refund',
    amount: 100,
    reservationTotal: 260,
    notes: 'استرجاع العربون بعد إعادة الفستان بحالة ممتازة.',
  },
  {
    id: 'pay-6',
    paymentNumber: 'PAY-2026-1006',
    reservationNumber: 'RES-2026-051',
    customerName: 'سارة أحمد',
    dressCode: 'DR-019',
    dressName: 'فستان سهرة فضي',
    paymentDate: '2026-05-19',
    type: 'adjustment',
    method: 'other',
    direction: 'income',
    amount: 10,
    reservationTotal: 340,
    notes: 'تعديل سعر لخدمة تجهيز إضافية.',
  },
  {
    id: 'pay-7',
    paymentNumber: 'PAY-2026-1007',
    reservationNumber: 'RES-2026-046',
    customerName: 'ليان مازن',
    dressCode: 'DR-011',
    dressName: 'فستان دانتيل عاجي',
    paymentDate: '2026-05-08',
    type: 'rental',
    method: 'card',
    direction: 'income',
    amount: 160,
    reservationTotal: 260,
    notes: 'تسديد قيمة الإيجار.',
  },
];
